// a/angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import * as moment from 'moment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  public today = '';

  ngOnInit(): void {
    this.changeLocale('mn');
  }

  changeLocale(locale: string): void {
    moment.locale(locale);
    this.today = moment().format('ll');
  }
}

<div class="wrapper">
  <div class="title">
    Angular
    <a href="https://github.com/javkhaanj7/minimalist-developer/tree/master/a/angular-app" target="_blank">
      <fa-icon [icon]="faCodeBranch"></fa-icon>
    </a>
  </div>
  <div class="flag">
    <span class="flag-icon flag-icon-mn" (click)="changeLocale('mn')"></span>
    <span class="flag-icon flag-icon-gb" (click)="changeLocale('en')"></span>
  </div>
  <div class="date">
    <fa-icon [icon]="faClock"></fa-icon>
    {{today}}
  </div>
</div>

// b/react-app/src/App.js
import React, { Component } from 'react';
import './App.css';
import moment from 'moment';
import 'moment/min/locales';

class App extends Component {

  constructor() {
    super();
    moment.locale('mn');
    this.state = {
      today: moment().format('ll')
    };
    this.changeLocale = this.changeLocale.bind(this);
  }

  changeLocale(locale) {
    moment.locale(locale);
    this.setState({ today: moment().format('ll') });
  }

  render() {
    return (
      <div className="wrapper">
        <div className="title">
          React <a rel="noreferrer" href="https://github.com/javkhaanj7/minimalist-developer/tree/master/b/react-app" target="_blank">
            <i className="fa fa-code-fork" aria-hidden="true"></i>
          </a>
        </div>
        <div className="flag">
          <span className="flag-icon flag-icon-mn" onClick={() => this.changeLocale('mn')}></span>
          <span className="flag-icon flag-icon-gb" onClick={() => this.changeLocale('en')}></span>
        </div>
        <div className="date">
          <i className="fa fa-clock-o" aria-hidden="true"></i> {this.state.today}
        </div>
      </div>
    )
  }
}

export default App;
