// a/vue-app/src/App.vue
<template>
  <div class="wrapper">
    <div class="title">
      Vue.js
      <a
        href="https://github.com/javkhaanj7/minimalist-developer/tree/master/a/vue-app"
        target="_blank"
      >
        <i class="fa fa-code-fork" aria-hidden="true"></i>
      </a>
    </div>
    <div class="flag">
      <span
        class="flag-icon flag-icon-mn"
        v-on:click="changeLocale('mn')"
      ></span>
      <span
        class="flag-icon flag-icon-gb"
        v-on:click="changeLocale('en')"
      ></span>
    </div>
    <div class="date">
      <i class="fa fa-clock-o" aria-hidden="true"></i>
      {{ today }}
    </div>
  </div>
</template>

<script>
import moment from "moment";

moment.locale("mn");

export default {
  name: "App",
  data: function () {
    return {
      today: moment().format("ll"),
    };
  },
  methods: {
    changeLocale(locale) {
      moment.locale(locale);
      this.today = moment().format("ll");
    },
  },
};
</script>

<style>
html,
body,
#app {
  height: 100%;
  margin: 0;
}

body {
  background-color: #41b883;
}

a {
  color: #dcdcdc;
  text-decoration: none;
}

.wrapper {
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}

.wrapper .title {
  margin: 10px 0px;
  font-size: 62px;
  color: white;
}

.wrapper .flag {
  margin: 10px 0px;
}

.wrapper .flag .flag-icon {
  margin: 0 4px;
}

.wrapper .flag .flag-icon:hover {
  cursor: pointer;
}

.wrapper .date {
  margin: 10px 0px;
  color: white;
}

.wrapper .flag,
.wrapper .date {
  font-size: 18px;
}
</style>

// a/react-app/src/App.js
import React, { Component } from 'react';
import './App.css';
import moment from 'moment';
import 'moment/min/locales';

class App extends Component {

  constructor() {
    super();
    moment.locale('mn');
    this.state = {
      today: moment().format('ll')
    };
    this.changeLocale = this.changeLocale.bind(this);
  }

  changeLocale(locale) {
    moment.locale(locale);
    this.setState({ today: moment().format('ll') });
  }

  render() {
    return (
      <div className="wrapper">
        <div className="title">
          React <a rel="noreferrer" href="https://github.com/javkhaanj7/minimalist-developer/tree/master/a/react-app" target="_blank">
            <i className="fa fa-code-fork" aria-hidden="true"></i>
          </a>
        </div>
        <div className="flag">
          <span className="flag-icon flag-icon-mn" onClick={() => this.changeLocale('mn')}></span>
          <span className="flag-icon flag-icon-gb" onClick={() => this.changeLocale('en')}></span>
        </div>
        <div className="date">
          <i className="fa fa-clock-o" aria-hidden="true"></i> {this.state.today}
        </div>
      </div>
    )
  }
}

export default App;
